"""
Device Registration Helper
Run this script to generate credentials for a new PC/device.
"""
import uuid
import secrets
import time
from firebase_config import get_firestore_db, initialize_firebase

def generate_device_credentials(user_id, device_name=None):
    """
    Generate unique device credentials
    
    Args:
        user_id: Firebase user ID (get from Firebase Console or mobile app)
        device_name: Optional friendly name for the device
    
    Returns:
        dict with device_id and device_token
    """
    # Generate unique device ID and token
    device_id = str(uuid.uuid4())
    device_token = secrets.token_urlsafe(32)
    
    # Store in Firestore (optional but recommended)
    try:
        if initialize_firebase():
            db = get_firestore_db()
            device_doc = db.collection('users').document(user_id).collection('devices').document(device_id)
            device_doc.set({
                'device_id': device_id,
                'device_name': device_name or 'Unknown Device',
                'created_at': time.time(),
                'status': 'registered',
                'token_hash': secrets.token_hex(16)  # Don't store actual token
            })
            print("✅ Device registered in Firestore")
    except Exception as e:
        print(f"⚠️ Warning: Could not register in Firestore: {e}")
        print("⚠️ Device will still work, but won't be visible in database")
    
    return {
        'device_id': device_id,
        'device_token': device_token
    }

def save_to_env_file(user_id, device_id, device_token):
    """Save credentials to .env file"""
    env_content = f"""# Device Configuration
DEVICE_ID={device_id}
USER_ID={user_id}
DEVICE_TOKEN={device_token}

# Generated by device_register.py
# Keep this file secure and never commit to git
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ Credentials saved to .env file")

def main():
    print("=" * 60)
    print("Device Registration Helper")
    print("=" * 60)
    print("\nThis script will generate credentials for your PC.")
    print("You'll need your Firebase User ID.\n")
    
    # Get user ID
    print("To find your User ID:")
    print("1. Log into the mobile app")
    print("2. Go to Profile/Settings")
    print("3. Copy your User ID")
    print("\nOr get it from Firebase Console > Authentication > Users\n")
    
    user_id = input("Enter your User ID: ").strip()
    
    if not user_id:
        print("❌ Error: User ID is required")
        return
    
    # Get device name (optional)
    device_name = input("Enter device name (e.g., 'My Laptop', 'Gaming PC'): ").strip()
    if not device_name:
        import platform
        device_name = f"{platform.system()} - {platform.node()}"
    
    print(f"\n🔧 Generating credentials for: {device_name}")
    
    # Generate credentials
    creds = generate_device_credentials(user_id, device_name)
    
    # Save to .env
    save_to_env_file(user_id, creds['device_id'], creds['device_token'])
    
    print("\n" + "=" * 60)
    print("✅ Device Registration Complete!")
    print("=" * 60)
    print(f"\nDevice ID: {creds['device_id']}")
    print(f"Device Name: {device_name}")
    print(f"\n⚠️  IMPORTANT:")
    print("   - Keep the .env file secure")
    print("   - Don't share your device token")
    print("   - Now you can run agent.py")
    print("=" * 60)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Registration cancelled")
    except Exception as e:
        print(f"\n❌ Error: {e}")
